"use client";
import { useState, useTransition } from "react";
import { savePaymentSettings } from "./actions";
import { methods, type PaymentPolicy, type PaymentSettings } from "./policy";
export default function PaymentSettingsClient({initialSettings}:{initialSettings:PaymentSettings|null}) {
 const [settings,setSettings]=useState(initialSettings);
 const [message,setMessage]=useState("");
 const [pending,startTransition]=useTransition();
 if (!settings) return <section className="card financePanel"><h2>الإعدادات الأساسية للمنشأة غير مهيأة.</h2><p>يجب تهيئة بيانات المنشأة قبل حفظ سياسة الدفع.</p><button className="button primary" disabled>حفظ إعدادات الدفع</button></section>;
 const policy=settings.payment_policy;
 const blocked=settings.payment_domain_enabled || settings.gateway_enabled || pending;
 function change(update:Partial<PaymentPolicy>) {setSettings(s=>s ? {...s,payment_policy:{...s.payment_policy,...update}} : s);setMessage("");}
 return <form onSubmit={event=>{event.preventDefault();if(blocked)return;if(!policy.allowed_methods.length){setMessage("اختر طريقة دفع واحدة على الأقل.");return;}startTransition(async()=>{const result=await savePaymentSettings(policy,settings.payment_policy_version,settings.gateway_provider);setMessage(result.message);if(result.ok && result.version)setSettings(s=>s ? {...s,payment_policy_version:result.version!} : s);});}}>
 <section className="card financePanel"><p>إعداد هذه السياسة لا يفعّل الدفع الإلكتروني ولا يغيّر رحلة العميل حتى اكتمال المراحل التالية.</p><p>إصدار العقد: {policy.schema_version} — إصدار السياسة: {settings.payment_policy_version}</p></section>
 <fieldset disabled={blocked} style={{border:0,padding:0,margin:0}}>
 <section className="card financePanel"><h2>سياسة الدفع</h2><div className="financeGrid"><label>توقيت الدفع<select value={policy.original_timing} onChange={e=>{const timing=e.target.value as PaymentPolicy["original_timing"];change({original_timing:timing,...(timing==="pay_on_arrival"?{allow_pay_on_arrival:true}:{}),...(timing==="pay_after_completion"?{allow_pay_after_completion:true}:{})});}}><option value="customer_choice">اختيار العميل</option><option value="prepay_required">الدفع المسبق إلزامي</option><option value="pay_on_arrival">الدفع عند وصول الفني</option><option value="pay_after_completion">الدفع بعد التنفيذ</option></select></label></div></section>
 <section className="card financePanel"><h2>توقيت التحصيل</h2><p><label><input type="checkbox" checked={policy.allow_pay_on_arrival} disabled={policy.original_timing==="pay_on_arrival"} onChange={e=>change({allow_pay_on_arrival:e.target.checked})}/> السماح بالدفع عند وصول الفني</label></p><p><label><input type="checkbox" checked={policy.allow_pay_after_completion} disabled={policy.original_timing==="pay_after_completion"} onChange={e=>change({allow_pay_after_completion:e.target.checked})}/> السماح بالدفع بعد التنفيذ</label></p></section>
 <section className="card financePanel"><h2>رسوم الفحص والاسترداد</h2><ul><li>رسوم الفحص تُحتسب ضمن العمل النهائي</li><li>تبقى رسوم الفحص المستحقة عند رفض العمل</li><li>يُسترد المبلغ الزائد</li></ul><p>قواعد ثابتة في السياسة الحالية.</p></section>
 <section className="card financePanel"><h2>الأعمال الإضافية</h2><div className="financeGrid"><label>توقيت الدفع<select value={policy.additional_timing} onChange={e=>change({additional_timing:e.target.value as PaymentPolicy["additional_timing"]})}><option value="customer_choice">اختيار العميل</option><option value="before_execution">قبل التنفيذ</option><option value="after_execution">بعد التنفيذ</option></select></label></div><label><input type="checkbox" checked={policy.allow_work_before_balance} onChange={e=>change({allow_work_before_balance:e.target.checked})}/> السماح ببدء العمل قبل سداد الرصيد</label></section>
 <section className="card financePanel"><h2>طرق الدفع</h2>{methods.map(method=><p key={method.value}><label><input type="checkbox" checked={policy.allowed_methods.includes(method.value)} onChange={e=>change({allowed_methods:e.target.checked ? [...new Set([...policy.allowed_methods,method.value])] : policy.allowed_methods.filter(v=>v!==method.value)})}/> {method.label}</label></p>)}<p>البطاقة تصنيف لسجل التحصيل فقط؛ الدفع الإلكتروني غير مفعّل.</p></section>
 <section className="card financePanel"><h2>إعدادات بوابة الدفع</h2><div className="financeGrid"><label>اسم المزود (اختياري وغير سري)<input maxLength={100} value={settings.gateway_provider??""} onChange={e=>setSettings({...settings,gateway_provider:e.target.value||null})}/></label><label>البيئة<input value="test" readOnly/></label></div><p>لا تدخل مفاتيح API أو كلمات مرور أو أسرار اعتماد.</p><p>البوابة: {settings.gateway_enabled?"مفعلة — الحفظ محظور":"غير مفعلة"}</p><p>مسار الدفع: {settings.payment_domain_enabled?"مفعّل — الحفظ محظور":"غير مفعّل"}</p></section>
 </fieldset><section className="card financePanel"><button type="submit" className="button primary" disabled={blocked}>{pending?"جارٍ الحفظ...":"حفظ إعدادات الدفع"}</button>{message && <p role="status" aria-live="polite">{message}</p>}</section>
 </form>;
}
