"use client";
import {useState} from "react";
import {methodLabels,statusLabels,technicianCollectionActivationReady,type PaymentOperations} from "@/lib/technician-collections";
import {decidePaymentOperation,loadPaymentOperations} from "./actions";
export default function PaymentOperationsClient({initialContext}:{initialContext:PaymentOperations}){
 const [context,setContext]=useState(initialContext);const [message,setMessage]=useState("");const [pending,setPending]=useState(false);const [reasons,setReasons]=useState<Record<string,string>>({});const [keys,setKeys]=useState<Record<string,string>>({});
 const disabled=!context.payment_domain_enabled||!technicianCollectionActivationReady||pending;
 async function reload(offset:number){setPending(true);const result=await loadPaymentOperations(offset);if(result.ok)setContext(result.context);else setMessage(result.message);setPending(false);}
 async function act(id:string,operation:"settle"|"verify"|"reject"|"post"|"void"){if(disabled)return;setPending(true);const key=keys[id]||crypto.randomUUID();setKeys(old=>({...old,[id]:key}));const result=await decidePaymentOperation(id,operation,key,reasons[id]??"");setMessage(result.message);if(result.ok){const fresh=await loadPaymentOperations(context.offset);if(fresh.ok)setContext(fresh.context);}setPending(false);}
 return <section className="collectionOperations" aria-label="عمليات التحصيل">{disabled?<p role="status">وضع التجهيز فقط — إجراءات التحصيل والتسوية غير مفعّلة.</p>:null}
 {(["cash","noncash"] as const).map(group=><section key={group}><h2>{group==="cash"?"عهدة نقدية بانتظار التسوية":"تحصيل غير نقدي بانتظار التحقق أو التسجيل المالي"}</h2>{context.operations.filter(row=>(row.method==="cash") === (group==="cash")).map(row=><article className="card" key={row.id}><h3>{row.technician_name}</h3><p>الطلب: <bdi>{row.request_id}</bdi></p><p>{methodLabels[row.method]} — {row.amount} {row.currency}</p><p>{statusLabels[row.status]}</p><p>التسجيل المالي: {row.posting_state==="posted"?"مسجل":"لا يوجد إيصال مؤكد"}</p><p>المصدر: تحصيل فني — <bdi>{row.id}</bdi></p><p>وقت التحصيل: <bdi>{row.collected_at}</bdi></p>{row.block_reason?<p>العملية تحتاج مراجعة أو أن المسار غير مفعّل.</p>:null}
 <label>سبب الرفض أو إبطال السجل<input value={reasons[row.id]??""} maxLength={500} disabled={disabled} onChange={e=>setReasons(old=>({...old,[row.id]:e.target.value}))}/></label><div className="collectionActionButtons">{(row.method==="cash"?["settle","void"]:row.status==="verified"?["post"]:["verify","reject"]).map(op=><button key={op} type="button" className="button secondary" disabled={disabled} onClick={()=>act(row.id,op as "settle"|"verify"|"reject"|"post"|"void")}>{({settle:"تسوية",void:"إبطال سجل العهدة",verify:"تحقق",reject:"رفض",post:"تسجيل الإيصال"} as Record<string,string>)[op]}</button>)}</div></article>)}{!context.operations.some(row=>(row.method==="cash") === (group==="cash"))?<p>لا توجد عمليات في هذه المجموعة.</p>:null}</section>)}
 <div className="collectionActionButtons"><button type="button" disabled={pending||context.offset===0} onClick={()=>reload(Math.max(0,context.offset-50))}>السابق</button><button type="button" disabled={pending||context.operations.length<50} onClick={()=>reload(context.offset+50)}>التالي</button></div><p role="status">{message}</p></section>;
}
