"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";
type Item={id:string;service_key:string;name:string;description:string;price_from:number|null;pricing_mode:"fixed"|"from"|"inspection";is_visible:boolean;sort_order:number;parent_id:string|null};
type Part={id:string;service_catalog_item_id:string;name:string;default_price:number;is_active:boolean;sort_order:number};
export default function CatalogManager({initialItems,initialParts}:{initialItems:Item[];initialParts:Part[]}){
 const [items,setItems]=useState(initialItems),[parts,setParts]=useState(initialParts),[busy,setBusy]=useState(false),[message,setMessage]=useState(""); const db=createClient();
 const patchItem=(id:string,u:Partial<Item>)=>setItems(rows=>rows.map(x=>x.id===id?{...x,...u}:x)); const patchPart=(id:string,u:Partial<Part>)=>setParts(rows=>rows.map(x=>x.id===id?{...x,...u}:x)); const main=items.filter(x=>!x.parent_id);
 async function addPart(serviceId:string){const {data,error}=await db.from("service_catalog_parts").insert({service_catalog_item_id:serviceId,name:"قطعة جديدة",default_price:0,sort_order:parts.filter(x=>x.service_catalog_item_id===serviceId).length}).select().single();if(error||!data){setMessage("تعذر إضافة القطعة.");return}setParts(rows=>[...rows,data as Part])}
 async function save(){setBusy(true);const [{error:a},{error:b}]=await Promise.all([db.from("service_catalog_items").upsert(items),db.from("service_catalog_parts").upsert(parts)]);setBusy(false);setMessage(a||b?"تعذر حفظ بعض التغييرات.":"تم حفظ الخدمات والقطع والأسعار.")}
 return <section className="card" style={{maxWidth:980}}><p className="adminIntro">لكل خدمة رئيسية قائمة قطع شائعة وسعر افتراضي. يستخدم عرض السعر هذا السعر تلقائيًا، مع بقاء التعديل اليدوي ممكنًا للحالة المحددة.</p>{items.map(item=><article className="builderItem" key={item.id}><label>اسم الخدمة<input value={item.name} onChange={e=>patchItem(item.id,{name:e.target.value})}/></label><label>تصنيف الخدمة<select value={item.parent_id??""} onChange={e=>patchItem(item.id,{parent_id:e.target.value||null})}><option value="">خدمة رئيسية</option>{main.filter(x=>x.id!==item.id).map(x=><option key={x.id} value={x.id}>خدمة فرعية من: {x.name}</option>)}</select></label><label>الوصف<textarea value={item.description} onChange={e=>patchItem(item.id,{description:e.target.value})}/></label></article>)}<h2>قطع الغيار الشائعة</h2>{main.map(service=><section key={service.id} className="builderItem" style={{display:"block"}}><strong>{service.name}</strong>{parts.filter(p=>p.service_catalog_item_id===service.id).map(part=><div className="technicianResponseControl" key={part.id}><label>القطعة<input value={part.name} onChange={e=>patchPart(part.id,{name:e.target.value})}/></label><label>السعر الافتراضي<input type="number" min="0" step="0.01" value={part.default_price} onChange={e=>patchPart(part.id,{default_price:Number(e.target.value)||0})}/></label><label><input type="checkbox" checked={part.is_active} onChange={e=>patchPart(part.id,{is_active:e.target.checked})}/> متاحة للاختيار</label></div>)}<button className="button secondary compactButton" type="button" onClick={()=>addPart(service.id)}>إضافة قطعة</button></section>)}<button className="button primary" type="button" disabled={busy} onClick={save}>{busy?"جارٍ الحفظ...":"حفظ التغييرات"}</button>{message?<p role="status">{message}</p>:null}</section>;
}
