-- M7 only. Authorized Test target: wsjmaojgjzxkmxywvcfy.
-- No financial function bodies, policies, defaults, workflow or lifecycle changes.
-- Existing authenticated SELECT and service_role contracts are preserved.
SET LOCAL lock_timeout = '5s';
REVOKE ALL PRIVILEGES ON TABLE public.finance_charge_reviews FROM PUBLIC, anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE public.finance_charge_reviews FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.payment_attempts FROM PUBLIC, anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE public.payment_attempts FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.payment_refunds FROM PUBLIC, anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE public.payment_refunds FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.technician_collections FROM PUBLIC, anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE public.technician_collections FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.business_finance_settings FROM PUBLIC, anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE public.business_finance_settings FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.service_request_quotes FROM PUBLIC, anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE public.service_request_quotes FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.invoice_payments FROM PUBLIC, anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE public.invoice_payments FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.invoices FROM PUBLIC, anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE public.invoices FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.invoice_line_items FROM PUBLIC, anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE public.invoice_line_items FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.service_requests FROM PUBLIC, anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE public.service_requests FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.service_request_change_requests FROM PUBLIC, anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE public.service_request_change_requests FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.service_request_items FROM PUBLIC, anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE public.service_request_items FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.service_request_change_items FROM PUBLIC, anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE public.service_request_change_items FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.service_request_payments FROM PUBLIC, anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE public.service_request_payments FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.finance_expenses FROM PUBLIC, anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE public.finance_expenses FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE private.payment_audit_events FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_invoice_line_signature(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_guard_invoice_basis() FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_invalidate_invoice_line_basis() FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.finance_seed_invoice_from_approved_quote(uuid,uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_audit_foundation() FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.finance_transfer_request_payments_to_invoice(uuid,uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_validate_settings_policy() FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_snapshot_request_policy() FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_snapshot_item_classification() FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_foundation_context(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_policy_v1_is_valid(jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_write_audit_event(text,text,uuid,uuid,uuid,jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_audit_forbid_mutation() FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.finance_guard_charge_review() FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.finance_audit_charge_review() FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_foundation_amount_valid(numeric) FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_foundation_require_finance() FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_create_attempt(uuid,numeric,text,text,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_transition_attempt(uuid,text,text,numeric,text,uuid,uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_guard_refund() FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_transition_refund(uuid,text,text,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_guard_attempt() FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_check_receipt_reverse_link() FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_guard_receipt_provenance() FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_post_verified_attempt(uuid,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_compose_full_work_lines(uuid,uuid[]) FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_guard_financial_quote() FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_advance_quote_revision() FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_require_assigned_technician(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_inspection_snapshot_amount(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_guard_workflow_evidence() FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_guard_collection() FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_invoice_basis_matches(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_financial_state(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_prove_resolved_untransferred(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_charge_review_revision() FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION private.payment_post_technician_collection(uuid,text,boolean) FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON FUNCTION public.finance_settle_technician_cash_collection(uuid,text) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.finance_post_verified_technician_collection(uuid,text) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.finance_save_settings(text,text,text,text,numeric,boolean) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.finance_get_summary() FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.admin_submit_service_request_quote(uuid,text,text,numeric,numeric) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.customer_decide_service_request_quote(uuid,boolean,text) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.finance_create_invoice(uuid,text,numeric) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.finance_mark_invoice_emailed(uuid) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.finance_record_payment(uuid,numeric,text,text) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.finance_set_invoice_status(uuid,text) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.finance_record_expense(text,text,numeric,date,text,text,text,text,uuid) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.finance_void_expense(uuid) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.finance_void_technician_collection_record(uuid,text) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.admin_submit_service_request_quote(uuid,text,jsonb) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.finance_ensure_invoice_draft(uuid) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.finance_update_invoice_draft(uuid,text,jsonb) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.finance_void_service_request_payment(uuid) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.finance_void_payment(uuid) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.finance_get_invoice_list_summary() FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.finance_record_service_request_payment(uuid,numeric,text,text,text) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.finance_propose_charge_review(uuid,numeric,text,text,uuid) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.finance_decide_charge_review(uuid,boolean,text) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.finance_request_refund(uuid,uuid,uuid,numeric,text,text,text) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.finance_decide_refund(uuid,text) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.technician_record_collection(uuid,text,numeric,text,text,timestamp with time zone) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.finance_verify_technician_collection(uuid,boolean,text) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.admin_submit_full_final_work_quote(uuid,text,uuid[]) FROM PUBLIC, anon;
REVOKE ALL PRIVILEGES ON FUNCTION public.technician_confirm_inspection_earned(uuid) FROM PUBLIC, anon;
ALTER FUNCTION public.finance_save_settings(text,text,text,text,numeric,boolean) SET search_path = public, pg_temp;
ALTER FUNCTION public.finance_get_summary() SET search_path = public, pg_temp;
ALTER FUNCTION public.admin_submit_service_request_quote(uuid,text,text,numeric,numeric) SET search_path = public, pg_temp;
ALTER FUNCTION public.customer_decide_service_request_quote(uuid,boolean,text) SET search_path = public, pg_temp;
ALTER FUNCTION public.finance_create_invoice(uuid,text,numeric) SET search_path = public, pg_temp;
ALTER FUNCTION public.finance_mark_invoice_emailed(uuid) SET search_path = public, pg_temp;
ALTER FUNCTION public.finance_record_payment(uuid,numeric,text,text) SET search_path = public, pg_temp;
ALTER FUNCTION public.finance_get_invoice_list_summary() SET search_path = public, pg_temp;
-- Default privileges are deliberately unchanged: public defaults also serve non-finance application objects.
-- Legacy overloads retain authenticated/service_role contracts; no DROP or blind revoke.
CREATE INDEX m7_finance_expenses_created_by_idx ON public.finance_expenses (created_by);
CREATE INDEX m7_finance_expenses_voided_by_idx ON public.finance_expenses (voided_by);
CREATE INDEX m7_invoice_payments_recorded_by_idx ON public.invoice_payments (recorded_by);
CREATE INDEX m7_invoice_payments_voided_by_idx ON public.invoice_payments (voided_by);
CREATE INDEX m7_invoices_created_by_idx ON public.invoices (created_by);
CREATE INDEX m7_invoices_customer_id_idx ON public.invoices (customer_id);
CREATE INDEX m7_notifications_service_request_id_idx ON public.notifications (service_request_id);
CREATE INDEX m7_service_request_assignments_assigned_by_idx ON public.service_request_assignments (assigned_by);
CREATE INDEX m7_service_request_attachments_uploaded_by_idx ON public.service_request_attachments (uploaded_by);
CREATE INDEX m7_service_request_change_requests_reviewed_by_idx ON public.service_request_change_requests (reviewed_by);
CREATE INDEX m7_service_request_events_actor_id_idx ON public.service_request_events (actor_id);
CREATE INDEX m7_service_request_payments_recorded_by_idx ON public.service_request_payments (recorded_by);
CREATE INDEX m7_service_request_payments_voided_by_idx ON public.service_request_payments (voided_by);
CREATE INDEX m7_service_request_quotes_created_by_idx ON public.service_request_quotes (created_by);
CREATE INDEX m7_service_requests_archived_by_idx ON public.service_requests (archived_by);
CREATE INDEX m7_service_requests_cancellation_actor_id_idx ON public.service_requests (cancellation_actor_id);
CREATE INDEX m7_service_requests_completion_reviewed_by_idx ON public.service_requests (completion_reviewed_by);
CREATE INDEX m7_site_editor_versions_created_by_idx ON public.site_editor_versions (created_by);
CREATE INDEX m7_warranty_claims_invoice_id_idx ON public.warranty_claims (invoice_id);
